"""

Compare fm and analytic SMMs to testify if:
    - samples generated by fm actually lie on the SMMs
    - samples generated by fm actually cover all SMMs

This version reports the comparison separately for every analytical IK branch
GC=(GC2, GC4, GC6).

"""

import argparse
from itertools import product
from pathlib import Path

import matplotlib.pyplot as plt
import mujoco
import numpy as np

from evaluation.eval_7r_4d import correct_positions_mujoco, wrap_to_pi
from model.analytic_ik.analytic_ik_7dof import Analytical_IK_7DoF
from model.flow_matching import FMConfig, FlowMatching, load_data


T_7_SITE = np.array(
    [
        [-1.0, 0.0, 0.0, 0.000],
        [0.0, -1.0, 0.0, 0.000],
        [0.0, 0.0, 1.0, 0.045],
        [0.0, 0.0, 0.0, 1.000],
    ],
    dtype=float,
)

GC_BRANCHES = tuple(product((-1, 1), repeat=3))
GC_BRANCH_ARRAY = np.asarray(GC_BRANCHES, dtype=int)
BRANCH_LABELS = tuple(
    f"GC=({gc[0]},{gc[1]},{gc[2]})" for gc in GC_BRANCHES
)

COVERAGE_THRESHOLDS = np.array(
    [0.10, 0.25, 0.50, 1.00],
    dtype=float,
)


def to_numpy(value):
    if hasattr(value, "detach"):
        value = value.detach().cpu().numpy()
    return np.asarray(value, dtype=np.float64)


def sample_so3(number, rng):
    """Generate Haar-uniform rotations."""

    if number <= 0:
        raise ValueError("number must be positive")

    u = rng.random((number, 3))
    s = np.sqrt(u[:, 0])
    t = np.sqrt(1.0 - u[:, 0])
    a = 2.0 * np.pi * u[:, 1]
    b = 2.0 * np.pi * u[:, 2]

    x = t * np.sin(a)
    y = t * np.cos(a)
    z = s * np.sin(b)
    w = s * np.cos(b)

    rotations = np.empty((number, 3, 3), dtype=float)
    rotations[:, 0, 0] = 1.0 - 2.0 * (y * y + z * z)
    rotations[:, 0, 1] = 2.0 * (x * y - z * w)
    rotations[:, 0, 2] = 2.0 * (x * z + y * w)
    rotations[:, 1, 0] = 2.0 * (x * y + z * w)
    rotations[:, 1, 1] = 1.0 - 2.0 * (x * x + z * z)
    rotations[:, 1, 2] = 2.0 * (y * z - x * w)
    rotations[:, 2, 0] = 2.0 * (x * z - y * w)
    rotations[:, 2, 1] = 2.0 * (y * z + x * w)
    rotations[:, 2, 2] = 1.0 - 2.0 * (x * x + y * y)
    return rotations


def make_site_pose(position, rotation):
    T = np.eye(4, dtype=float)
    T[:3, :3] = rotation
    T[:3, 3] = position
    return T


def site_pose_to_dh_pose(T_site):
    return np.asarray(T_site, dtype=float) @ np.linalg.inv(T_7_SITE)


def pose_errors(T_a, T_b):
    position_error = np.linalg.norm(T_a[:3, 3] - T_b[:3, 3])
    rotation_error = np.linalg.norm(T_a[:3, :3] - T_b[:3, :3])
    return float(position_error), float(rotation_error)


def fm_condition_from_pose(position, rotation, x_dim):
    if x_dim == 3:
        return np.asarray(position, dtype=float)
    if x_dim == 9:
        return np.concatenate(
            [
                np.asarray(position, dtype=float),
                np.asarray(rotation, dtype=float)[:2].reshape(6),
            ]
        )
    raise ValueError(
        "This comparison supports FM conditioning dimensions 3 and 9, "
        f"but received x_dim={x_dim}."
    )


def mujoco_positions(robot_cfg, qs):
    qs = to_numpy(qs)
    if qs.ndim == 1:
        qs = qs[None, :]
    if qs.ndim != 2 or qs.shape[1] != 7:
        raise ValueError("qs must have shape (N, 7).")

    model = robot_cfg.robot
    data = mujoco.MjData(model)
    qpos_ids = [model.jnt_qposadr[jid] for jid in robot_cfg._jnt_ids]

    if robot_cfg.ee_type == "site":
        ee_id = model.site(robot_cfg.ee_name).id
    elif robot_cfg.ee_type == "body":
        ee_id = model.body(robot_cfg.ee_name).id
    else:
        raise ValueError(f"Invalid ee_type: {robot_cfg.ee_type}")

    positions = np.empty((len(qs), 3), dtype=float)

    for index, q in enumerate(qs):
        data.qpos[:] = 0.0
        data.qpos[qpos_ids] = q
        mujoco.mj_forward(model, data)

        if robot_cfg.ee_type == "site":
            positions[index] = data.site_xpos[ee_id]
        else:
            positions[index] = data.xpos[ee_id]

    return positions


def _empty_branch_counts():
    return {
        "attempted": 0,
        "infeasible": 0,
        "joint_limit_rejected": 0,
        "pose_rejected": 0,
        "exceptions": 0,
        "accepted": 0,
    }


def analytic_smm_samples(
    ik,
    target_position,
    rotations,
    psi_samples,
    *,
    pose_tolerance=1e-5,
    acos_tolerance=1e-8,
    enforce_joint_limits=False,
):
    """Sample the analytical SMM while retaining the GC branch identity."""

    target_position = np.asarray(target_position, dtype=float)
    rotations = np.asarray(rotations, dtype=float)
    psi_samples = np.asarray(psi_samples, dtype=float)

    q_values = []
    orientation_indices = []
    gc_values = []
    psi_values = []

    counts = _empty_branch_counts()
    branch_counts = {
        gc_tuple: _empty_branch_counts() for gc_tuple in GC_BRANCHES
    }

    for orientation_index, rotation in enumerate(rotations):
        T_site = make_site_pose(target_position, rotation)
        T_dh = site_pose_to_dh_pose(T_site)

        for gc_tuple in GC_BRANCHES:
            GC = np.asarray(gc_tuple, dtype=int)
            branch_count = branch_counts[gc_tuple]

            for psi in psi_samples:
                counts["attempted"] += 1
                branch_count["attempted"] += 1

                try:
                    unclipped = np.asarray(
                        ik.IK(
                            rigid_transform=T_dh,
                            GC=GC,
                            psi=float(psi),
                            return_unclipped_vals=True,
                            clip_stepback=0.0,
                        ),
                        dtype=float,
                    )

                    if unclipped.shape != (4,):
                        counts["exceptions"] += 1
                        branch_count["exceptions"] += 1
                        continue

                    if np.any(np.abs(unclipped) > 1.0 + acos_tolerance):
                        counts["infeasible"] += 1
                        branch_count["infeasible"] += 1
                        continue

                    q = np.asarray(
                        ik.IK(
                            rigid_transform=T_dh,
                            GC=GC,
                            psi=float(psi),
                            clip_stepback=0.0,
                        ),
                        dtype=float,
                    )

                    if q.shape != (7,) or not np.all(np.isfinite(q)):
                        counts["pose_rejected"] += 1
                        branch_count["pose_rejected"] += 1
                        continue

                    if enforce_joint_limits:
                        inside_limits = (
                            np.all(q >= ik.limits_lower - 1e-8)
                            and np.all(q <= ik.limits_upper + 1e-8)
                        )
                        if not inside_limits:
                            counts["joint_limit_rejected"] += 1
                            branch_count["joint_limit_rejected"] += 1
                            continue

                    T_check = np.asarray(ik.FK(q), dtype=float)
                    position_error, rotation_error = pose_errors(
                        T_check,
                        T_dh,
                    )

                    if (
                        position_error > pose_tolerance
                        or rotation_error > pose_tolerance
                    ):
                        counts["pose_rejected"] += 1
                        branch_count["pose_rejected"] += 1
                        continue

                    q_values.append(q.copy())
                    orientation_indices.append(orientation_index)
                    gc_values.append(GC.copy())
                    psi_values.append(float(psi))
                    counts["accepted"] += 1
                    branch_count["accepted"] += 1

                except Exception:
                    counts["exceptions"] += 1
                    branch_count["exceptions"] += 1

    q_array = (
        np.asarray(q_values, dtype=float).reshape(-1, 7)
        if q_values
        else np.empty((0, 7), dtype=float)
    )
    orientation_array = np.asarray(orientation_indices, dtype=int)
    gc_array = (
        np.asarray(gc_values, dtype=int).reshape(-1, 3)
        if gc_values
        else np.empty((0, 3), dtype=int)
    )
    psi_array = np.asarray(psi_values, dtype=float)

    branch_qs = {}
    for gc_tuple in GC_BRANCHES:
        mask = np.all(gc_array == np.asarray(gc_tuple), axis=1)
        branch_qs[gc_tuple] = q_array[mask]

    return {
        "q": q_array,
        "orientation_index": orientation_array,
        "GC": gc_array,
        "psi": psi_array,
        "branch_qs": branch_qs,
        "counts": counts,
        "branch_counts": branch_counts,
    }


def torus_embedding(q):
    q = wrap_to_pi(to_numpy(q))
    if q.ndim == 1:
        q = q[None, :]
    return np.concatenate((np.sin(q), np.cos(q)), axis=1)


def nearest_torus_distances(query, reference, candidates=64):
    """Return nearest wrapped joint-space distances."""

    query = to_numpy(query)
    reference = to_numpy(reference)

    if query.ndim == 1:
        query = query[None, :]
    if reference.ndim == 1:
        reference = reference[None, :]
    if len(query) == 0:
        return np.empty((0,), dtype=float)
    if len(reference) == 0:
        return np.full(len(query), np.inf, dtype=float)

    try:
        from scipy.spatial import cKDTree

        tree = cKDTree(torus_embedding(reference))
        k = min(candidates, len(reference))
        _, indices = tree.query(torus_embedding(query), k=k)
        if k == 1:
            indices = indices[:, None]

        valid = indices < len(reference)
        indices = np.clip(indices, 0, len(reference) - 1)
        differences = wrap_to_pi(query[:, None, :] - reference[indices])
        distances = np.linalg.norm(differences, axis=2)
        distances[~valid] = np.inf
        return np.min(distances, axis=1)
    except ImportError:
        result = np.full(len(query), np.inf, dtype=float)
        for start in range(0, len(query), 256):
            stop = min(start + 256, len(query))
            differences = wrap_to_pi(
                query[start:stop, None, :] - reference[None, :, :]
            )
            result[start:stop] = np.min(
                np.linalg.norm(differences, axis=2),
                axis=1,
            )
        return result


def branch_distance_matrix(query, branch_qs, candidates=64):
    if not branch_qs:
        return np.empty((len(query), 0), dtype=float)
    return np.column_stack(
        [
            nearest_torus_distances(
                query,
                branch_qs[gc_tuple],
                candidates=candidates,
            )
            for gc_tuple in GC_BRANCHES
        ]
    )


def _finite_median(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    return float(np.median(values)) if len(values) else np.nan


def _finite_percentile(values, percentile):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    return float(np.percentile(values, percentile)) if len(values) else np.nan


def _nanmean(values):
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    return float(np.mean(values)) if len(values) else np.nan


def compare_branch_distances(
    corrected_q,
    branch_qs,
    *,
    candidates=64,
):
    """Compute both directions of the comparison for every GC branch."""

    corrected_q = to_numpy(corrected_q)
    if corrected_q.ndim == 1:
        corrected_q = corrected_q[None, :]

    fm_to_branch = branch_distance_matrix(
        corrected_q,
        branch_qs,
        candidates=candidates,
    )

    branch_to_fm = []
    branch_coverage = np.full(
        (len(GC_BRANCHES), len(COVERAGE_THRESHOLDS)),
        np.nan,
        dtype=float,
    )
    fm_to_branch_coverage = np.full_like(branch_coverage, np.nan)
    branch_fm_median = np.full(len(GC_BRANCHES), np.nan, dtype=float)
    branch_fm_p95 = np.full(len(GC_BRANCHES), np.nan, dtype=float)

    for branch_index, gc_tuple in enumerate(GC_BRANCHES):
        branch_q = branch_qs[gc_tuple]
        distances_to_fm = nearest_torus_distances(
            branch_q,
            corrected_q,
            candidates=candidates,
        )
        branch_to_fm.append(distances_to_fm)

        if len(branch_q) > 0:
            branch_coverage[branch_index] = [
                np.mean(distances_to_fm <= threshold)
                for threshold in COVERAGE_THRESHOLDS
            ]
            if len(corrected_q) > 0:
                fm_distances = fm_to_branch[:, branch_index]
                fm_to_branch_coverage[branch_index] = [
                    np.mean(fm_distances <= threshold)
                    for threshold in COVERAGE_THRESHOLDS
                ]

        if len(corrected_q) > 0 and len(branch_q) > 0:
            branch_fm_median[branch_index] = _finite_median(
                fm_to_branch[:, branch_index]
            )
            branch_fm_p95[branch_index] = _finite_percentile(
                fm_to_branch[:, branch_index],
                95.0,
            )

    if len(corrected_q) > 0 and fm_to_branch.shape[1] > 0:
        has_reference = np.any(np.isfinite(fm_to_branch), axis=1)
        nearest_branch_indices = np.full(len(corrected_q), -1, dtype=int)
        nearest_branch_distances = np.full(
            len(corrected_q),
            np.inf,
            dtype=float,
        )
        nearest_branch_indices[has_reference] = np.argmin(
            fm_to_branch[has_reference],
            axis=1,
        )
        nearest_branch_distances[has_reference] = np.min(
            fm_to_branch[has_reference],
            axis=1,
        )
    else:
        nearest_branch_indices = np.empty((0,), dtype=int)
        nearest_branch_distances = np.empty((0,), dtype=float)

    assignment_counts = np.bincount(
        nearest_branch_indices[nearest_branch_indices >= 0],
        minlength=len(GC_BRANCHES),
    )

    analytic_to_fm = (
        np.concatenate(branch_to_fm)
        if branch_to_fm
        else np.empty((0,), dtype=float)
    )

    branch_assigned_median = np.full(len(GC_BRANCHES), np.nan, dtype=float)
    branch_assigned_p95 = np.full(len(GC_BRANCHES), np.nan, dtype=float)
    for branch_index in range(len(GC_BRANCHES)):
        assigned = nearest_branch_indices == branch_index
        branch_assigned_median[branch_index] = _finite_median(
            nearest_branch_distances[assigned]
        )
        branch_assigned_p95[branch_index] = _finite_percentile(
            nearest_branch_distances[assigned],
            95.0,
        )

    coverage = np.array(
        [
            np.mean(analytic_to_fm <= threshold)
            if len(analytic_to_fm) > 0
            else np.nan
            for threshold in COVERAGE_THRESHOLDS
        ],
        dtype=float,
    )

    return {
        "fm_to_branch": fm_to_branch,
        "branch_to_fm": branch_to_fm,
        "nearest_branch_indices": nearest_branch_indices,
        "nearest_branch_distances": nearest_branch_distances,
        "assignment_counts": assignment_counts,
        "branch_coverage": branch_coverage,
        "fm_to_branch_coverage": fm_to_branch_coverage,
        "branch_fm_median": branch_fm_median,
        "branch_fm_p95": branch_fm_p95,
        "branch_assigned_median": branch_assigned_median,
        "branch_assigned_p95": branch_assigned_p95,
        "analytic_to_fm": analytic_to_fm,
        "coverage": coverage,
    }


def evaluate_target(
    fm,
    robot_cfg,
    ik,
    target_position,
    rotations,
    psi_samples,
    *,
    x_dim,
    n_samples,
    n_steps,
    enforce_joint_limits,
    correction_iters=3,
    pose_tolerance=1e-5,
    acos_tolerance=1e-8,
    distance_candidates=64,
):
    analytic = analytic_smm_samples(
        ik=ik,
        target_position=target_position,
        rotations=rotations,
        psi_samples=psi_samples,
        pose_tolerance=pose_tolerance,
        acos_tolerance=acos_tolerance,
        enforce_joint_limits=enforce_joint_limits,
    )

    raw_q_values = []
    valid_orientation_indices = np.unique(analytic["orientation_index"])

    if x_dim == 3:
        valid_orientation_indices = np.array([-1], dtype=int)

    for orientation_index in valid_orientation_indices:
        if orientation_index == -1:
            condition = fm_condition_from_pose(
                target_position,
                np.eye(3),
                x_dim,
            )
        else:
            condition = fm_condition_from_pose(
                target_position,
                rotations[orientation_index],
                x_dim,
            )

        sampled_q = to_numpy(
            fm.sample(
                condition,
                n_samples=n_samples,
                n_steps=n_steps,
            )
        )
        if sampled_q.ndim == 1:
            sampled_q = sampled_q[None, :]
        if sampled_q.ndim != 2 or sampled_q.shape[1] != 7:
            continue

        finite_mask = np.all(np.isfinite(sampled_q), axis=1)
        raw_q_values.append(sampled_q[finite_mask])

    if raw_q_values:
        raw_q = np.concatenate(raw_q_values, axis=0)
    else:
        raw_q = np.empty((0, 7), dtype=float)

    if len(raw_q) > 0:
        corrected_q = correct_positions_mujoco(
            robot_cfg=robot_cfg,
            qs=raw_q,
            target_positions=target_position,
            iters=correction_iters,
            lam=1e-1,
            max_step=0.25,
        )
        corrected_q = to_numpy(corrected_q)
    else:
        corrected_q = np.empty((0, 7), dtype=float)

    if enforce_joint_limits and len(corrected_q) > 0:
        limit_mask = (
            np.all(corrected_q >= ik.limits_lower - 1e-8, axis=1)
            & np.all(corrected_q <= ik.limits_upper + 1e-8, axis=1)
        )
        corrected_q = corrected_q[limit_mask]

    corrected_positions = mujoco_positions(robot_cfg, corrected_q)
    corrected_position_errors = np.linalg.norm(
        corrected_positions - target_position[None, :],
        axis=1,
    )

    branch_result = compare_branch_distances(
        corrected_q,
        analytic["branch_qs"],
        candidates=distance_candidates,
    )

    analytic_branch_counts = np.asarray(
        [
            analytic["branch_counts"][gc_tuple]["accepted"]
            for gc_tuple in GC_BRANCHES
        ],
        dtype=int,
    )
    analytic_branch_attempted = np.asarray(
        [
            analytic["branch_counts"][gc_tuple]["attempted"]
            for gc_tuple in GC_BRANCHES
        ],
        dtype=int,
    )

    return {
        "target_position": np.asarray(target_position, dtype=float),
        "raw_q": raw_q,
        "corrected_q": corrected_q,
        "corrected_position_errors": corrected_position_errors,
        "analytic_q": analytic["q"],
        "analytic_gc": analytic["GC"],
        "analytic_orientation_index": analytic["orientation_index"],
        "analytic_psi": analytic["psi"],
        "analytic_branch_qs": analytic["branch_qs"],
        "analytic_branch_counts": analytic_branch_counts,
        "analytic_branch_attempted": analytic_branch_attempted,
        "fm_to_analytic": branch_result["nearest_branch_distances"],
        "analytic_to_fm": branch_result["analytic_to_fm"],
        "fm_to_branch": branch_result["fm_to_branch"],
        "branch_to_fm": branch_result["branch_to_fm"],
        "nearest_branch_indices": branch_result["nearest_branch_indices"],
        "assignment_counts": branch_result["assignment_counts"],
        "branch_coverage": branch_result["branch_coverage"],
        "fm_to_branch_coverage": branch_result["fm_to_branch_coverage"],
        "branch_fm_median": branch_result["branch_fm_median"],
        "branch_fm_p95": branch_result["branch_fm_p95"],
        "branch_assigned_median": branch_result["branch_assigned_median"],
        "branch_assigned_p95": branch_result["branch_assigned_p95"],
        "coverage": branch_result["coverage"],
        "analytic_counts": analytic["counts"],
        "analytic_branch_counts_detail": analytic["branch_counts"],
    }


def concatenate(results, key, axis=0):
    arrays = [result[key] for result in results if len(result[key]) > 0]
    if not arrays:
        return np.empty((0,), dtype=float)
    return np.concatenate(arrays, axis=axis)


def stack_results(results, key):
    return np.stack([result[key] for result in results], axis=0)


def print_target_branch_summary(result):
    print("  Analytical branches")
    for branch_index, (gc_tuple, label) in enumerate(
        zip(GC_BRANCHES, BRANCH_LABELS)
    ):
        accepted = result["analytic_branch_counts"][branch_index]
        assigned = result["assignment_counts"][branch_index]
        median = result["branch_fm_median"][branch_index]
        p95 = result["branch_fm_p95"][branch_index]
        coverage = result["branch_coverage"][branch_index]
        coverage_text = ", ".join(
            f"{threshold:.2f}:{100.0 * value:.2f}%"
            if np.isfinite(value)
            else f"{threshold:.2f}:n/a"
            for threshold, value in zip(COVERAGE_THRESHOLDS, coverage)
        )
        print(
            f"    {label}: analytic={accepted}, "
            f"FM assigned={assigned}, "
            f"FM->branch median={median:.4f}, p95={p95:.4f}, "
            f"branch->FM [{coverage_text}]"
        )


def print_summary(results):
    fm_errors = concatenate(results, "corrected_position_errors")
    fm_to_analytic = concatenate(results, "fm_to_analytic")
    analytic_to_fm = concatenate(results, "analytic_to_fm")

    print()
    print("Corrected FM samples")
    print(f"  samples: {len(fm_errors)}")
    if len(fm_errors) > 0:
        print(f"  position error mean: {np.mean(fm_errors):.6e} m")
        print(f"  position error median: {np.median(fm_errors):.6e} m")
        print(
            "  position error <= 1e-4 m: "
            f"{100.0 * np.mean(fm_errors <= 1e-4):.2f}%"
        )
        print(
            "  position error <= 1e-3 m: "
            f"{100.0 * np.mean(fm_errors <= 1e-3):.2f}%"
        )

    if len(fm_to_analytic) > 0:
        print()
        print("FM samples relative to nearest analytical branch")
        print(
            "  nearest joint-torus distance median: "
            f"{_finite_median(fm_to_analytic):.6e} rad"
        )
        print(
            "  nearest joint-torus distance 95%: "
            f"{_finite_percentile(fm_to_analytic, 95.0):.6e} rad"
        )

    if len(analytic_to_fm) > 0:
        print()
        print("Analytical SMM covered by corrected FM samples")
        for threshold in COVERAGE_THRESHOLDS:
            value = np.mean(analytic_to_fm <= threshold)
            print(
                f"  distance <= {threshold:.2f} rad: "
                f"{100.0 * value:.2f}%"
            )

    branch_counts = stack_results(results, "analytic_branch_counts")
    branch_assignments = stack_results(results, "assignment_counts")
    branch_medians = stack_results(results, "branch_fm_median")
    branch_p95 = stack_results(results, "branch_fm_p95")
    branch_coverage = stack_results(results, "branch_coverage")

    total_fm = int(sum(len(result["corrected_q"]) for result in results))
    print()
    print("Per-branch comparison")
    print(
        "  branch                 analytic    FM assigned    "
        "FM->branch median/p95    branch->FM coverage"
    )
    for branch_index, label in enumerate(BRANCH_LABELS):
        analytic_count = int(np.sum(branch_counts[:, branch_index]))
        assigned_count = int(np.sum(branch_assignments[:, branch_index]))
        assigned_percent = (
            100.0 * assigned_count / total_fm if total_fm > 0 else np.nan
        )
        median = _nanmean(branch_medians[:, branch_index])
        p95 = _nanmean(branch_p95[:, branch_index])
        coverage = np.asarray(branch_coverage[:, branch_index], dtype=float)
        coverage_text = ", ".join(
            f"{threshold:.2f}:{100.0 * _nanmean(coverage[:, k]):.2f}%"
            if np.isfinite(_nanmean(coverage[:, k]))
            else f"{threshold:.2f}:n/a"
            for k, threshold in enumerate(COVERAGE_THRESHOLDS)
        )
        print(
            f"  {label:<22} {analytic_count:>8d}    "
            f"{assigned_count:>8d} ({assigned_percent:>6.2f}%)    "
            f"{median:>8.4f}/{p95:<8.4f}       {coverage_text}"
        )


def plot_comparison(results, output_path, projection=(5, 6)):
    """Save summary and branch-wise plots."""

    fm_errors = concatenate(results, "corrected_position_errors")
    fm_to_analytic = concatenate(results, "fm_to_analytic")
    branch_counts = stack_results(results, "analytic_branch_counts")
    branch_assignments = stack_results(results, "assignment_counts")
    branch_coverage = stack_results(results, "branch_coverage")
    branch_medians = stack_results(results, "branch_fm_median")
    branch_p95 = stack_results(results, "branch_fm_p95")

    mean_coverage = np.nanmean(branch_coverage, axis=0)
    total_assignments = np.sum(branch_assignments, axis=0)
    assignment_percent = (
        100.0 * total_assignments / np.sum(total_assignments)
        if np.sum(total_assignments) > 0
        else np.zeros(len(GC_BRANCHES))
    )

    fig, axes = plt.subplots(2, 2, figsize=(16, 10))
    axes = axes.ravel()

    if len(fm_errors) > 0:
        axes[0].hist(
            1000.0 * fm_errors,
            bins=40,
            color="tab:orange",
            alpha=0.8,
            edgecolor="black",
            linewidth=0.3,
        )
    axes[0].set_xlabel("Corrected FM position error (mm)")
    axes[0].set_ylabel("Number of samples")
    axes[0].set_title("Corrected FM samples on position SMM")
    axes[0].grid(axis="y", alpha=0.25)

    if len(fm_to_analytic) > 0:
        axes[1].hist(
            fm_to_analytic,
            bins=40,
            color="tab:purple",
            alpha=0.8,
            edgecolor="black",
            linewidth=0.3,
        )
    axes[1].set_xlabel("Nearest analytical branch distance (rad)")
    axes[1].set_ylabel("Number of samples")
    axes[1].set_title("Corrected FM to nearest GC branch")
    axes[1].grid(axis="y", alpha=0.25)

    image = axes[2].imshow(
        100.0 * mean_coverage,
        vmin=0.0,
        vmax=100.0,
        aspect="auto",
        cmap="viridis",
    )
    axes[2].set_xticks(range(len(COVERAGE_THRESHOLDS)))
    axes[2].set_xticklabels(
        [f"{threshold:.2f}" for threshold in COVERAGE_THRESHOLDS]
    )
    axes[2].set_yticks(range(len(BRANCH_LABELS)))
    axes[2].set_yticklabels(BRANCH_LABELS, fontsize=8)
    axes[2].set_xlabel("Distance threshold (rad)")
    axes[2].set_ylabel("Analytical branch")
    axes[2].set_title("Coverage of each analytical branch")
    for row in range(len(GC_BRANCHES)):
        for col in range(len(COVERAGE_THRESHOLDS)):
            value = mean_coverage[row, col]
            if np.isfinite(value):
                axes[2].text(
                    col,
                    row,
                    f"{100.0 * value:.1f}",
                    ha="center",
                    va="center",
                    color="white" if value < 0.55 else "black",
                    fontsize=8,
                )
    fig.colorbar(image, ax=axes[2], label="Coverage (%)")

    x = np.arange(len(GC_BRANCHES))
    mean_median = np.nanmean(branch_medians, axis=0)
    mean_p95 = np.nanmean(branch_p95, axis=0)
    axes[3].plot(
        x,
        mean_median,
        "o-",
        label="median FMâ†’branch",
    )
    axes[3].plot(
        x,
        mean_p95,
        "s--",
        label="95th percentile FMâ†’branch",
    )
    axes[3].set_xticks(x)
    axes[3].set_xticklabels(BRANCH_LABELS, rotation=45, ha="right", fontsize=8)
    axes[3].set_ylabel("Distance (rad)")
    axes[3].set_title("Distance to each analytical branch")
    axes[3].grid(alpha=0.25)
    axes[3].legend()

    fig.tight_layout()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    # fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)

    branch_output = output_path.with_name(
        f"{output_path.stem}_joint_projection{output_path.suffix}"
    )
    plot_branch_joint_projection(results, branch_output, projection=projection)


def plot_branch_joint_projection(results, output_path, projection=(5, 6)):
    """Plot analytical and assigned FM samples for every branch."""

    joint_x, joint_y = projection
    if not (0 <= joint_x < 7 and 0 <= joint_y < 7):
        raise ValueError("projection joints must be in [0, 6]")
    if joint_x == joint_y:
        raise ValueError("projection joints must be different")

    fig, axes = plt.subplots(2, 4, figsize=(16, 8), squeeze=False)
    max_points = 20_000

    for branch_index, (gc_tuple, label) in enumerate(
        zip(GC_BRANCHES, BRANCH_LABELS)
    ):
        ax = axes.ravel()[branch_index]
        for result in results:
            analytic_q = result["analytic_branch_qs"][gc_tuple]
            assigned = result["nearest_branch_indices"] == branch_index
            fm_q = result["corrected_q"][assigned]

            if len(analytic_q) > max_points:
                analytic_q = analytic_q[
                    np.linspace(
                        0,
                        len(analytic_q) - 1,
                        max_points,
                    ).astype(int)
                ]
            if len(fm_q) > max_points:
                fm_q = fm_q[
                    np.linspace(
                        0,
                        len(fm_q) - 1,
                        max_points,
                    ).astype(int)
                ]

            if len(analytic_q) > 0:
                ax.scatter(
                    wrap_to_pi(analytic_q[:, joint_x]),
                    wrap_to_pi(analytic_q[:, joint_y]),
                    s=2,
                    alpha=0.18,
                    color="tab:blue",
                    label="analytic" if result is results[0] else None,
                )
            if len(fm_q) > 0:
                ax.scatter(
                    wrap_to_pi(fm_q[:, joint_x]),
                    wrap_to_pi(fm_q[:, joint_y]),
                    s=2,
                    alpha=0.18,
                    color="tab:orange",
                    label="corrected FM" if result is results[0] else None,
                )

        ax.set_title(label)
        ax.set_xlim(-np.pi, np.pi)
        ax.set_ylim(-np.pi, np.pi)
        ax.set_xlabel(rf"$\theta_{{{joint_x + 1}}}$")
        ax.set_ylabel(rf"$\theta_{{{joint_y + 1}}}$")
        ax.grid(alpha=0.25)
        if branch_index == 0:
            ax.legend(markerscale=4)

    fig.suptitle(
        "Branch-wise analytical and corrected FM samples "
        f"($theta_{{{joint_x + 1}}}$ vs $theta_{{{joint_y + 1}}}$)",
        fontsize=14,
    )
    fig.tight_layout()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    # fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def save_metrics(results, output_path):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    target_positions = stack_results(results, "target_position")
    branch_counts = stack_results(results, "analytic_branch_counts")
    branch_attempted = stack_results(results, "analytic_branch_attempted")
    assignment_counts = stack_results(results, "assignment_counts")
    branch_coverage = stack_results(results, "branch_coverage")
    fm_to_branch_coverage = stack_results(
        results,
        "fm_to_branch_coverage",
    )
    branch_fm_median = stack_results(results, "branch_fm_median")
    branch_fm_p95 = stack_results(results, "branch_fm_p95")
    branch_assigned_median = stack_results(
        results,
        "branch_assigned_median",
    )
    branch_assigned_p95 = stack_results(results, "branch_assigned_p95")

    fm_target_indices = concatenate(
        [
            {
                "fm_target_index": np.full(
                    len(result["corrected_q"]),
                    target_index,
                    dtype=int,
                )
            }
            for target_index, result in enumerate(results)
        ],
        "fm_target_index",
    )

    np.savez_compressed(
        output_path,
        target_positions=target_positions,
        branch_gc=GC_BRANCH_ARRAY,
        branch_labels=np.asarray(BRANCH_LABELS),
        coverage_thresholds=COVERAGE_THRESHOLDS,
        analytic_branch_counts=branch_counts,
        analytic_branch_attempted=branch_attempted,
        fm_branch_assignment_counts=assignment_counts,
        branch_coverage=branch_coverage,
        fm_to_branch_coverage=fm_to_branch_coverage,
        branch_fm_median=branch_fm_median,
        branch_fm_p95=branch_fm_p95,
        branch_assigned_median=branch_assigned_median,
        branch_assigned_p95=branch_assigned_p95,
        corrected_position_errors=concatenate(
            results,
            "corrected_position_errors",
        ),
        fm_to_nearest_branch=concatenate(results, "fm_to_analytic"),
        nearest_branch_indices=concatenate(
            results,
            "nearest_branch_indices",
        ).astype(int, copy=False),
        fm_target_index=fm_target_indices.astype(int, copy=False),
        analytic_to_fm=concatenate(results, "analytic_to_fm"),
        analytic_q=concatenate(results, "analytic_q"),
        analytic_gc=concatenate(results, "analytic_gc").astype(int, copy=False),
        analytic_orientation_index=concatenate(
            results,
            "analytic_orientation_index",
        ).astype(int, copy=False),
        analytic_psi=concatenate(results, "analytic_psi"),
    )


def evaluate_4d(
    cfg,
    *,
    n_targets=1,
    n_samples=200_000,
    n_steps=100,
    n_analytic_orientations=512,
    n_analytic_psi=512,
    seed=42,
    enforce_joint_limits=False,
    correction_iters=3,
    pose_tolerance=1e-5,
    acos_tolerance=1e-8,
    distance_candidates=64,
    output_path="evaluation/fm_vs_analytic_4d_branches.png",
    metrics_path=None,
    projection=(5, 6),
):
    robot_cfg = cfg.load_robot

    if robot_cfg.x_dim not in (3, 9):
        raise ValueError(
            "This comparison expects a 3-D or 9-D FM task, "
            f"but x_dim={robot_cfg.x_dim}."
        )

    if robot_cfg.ee_type != "site":
        raise ValueError(
            "The analytical frame conversion in this file is calibrated "
            "for the MuJoCo end-effector site."
        )

    train, test, norm = load_data(cfg)
    del train

    test_targets = to_numpy(test.tensors[1])
    x_c = to_numpy(norm["x_c"])
    x_h = to_numpy(norm["x_h"])
    test_targets = test_targets * x_h + x_c
    test_targets = np.asarray(test_targets[:, :3], dtype=float)

    if len(test_targets) == 0:
        raise ValueError("The test set contains no target positions.")
    if n_targets <= 0:
        raise ValueError("n_targets must be positive.")

    rng = np.random.default_rng(seed)
    n_targets = min(n_targets, len(test_targets))
    selected_indices = rng.choice(
        len(test_targets),
        size=n_targets,
        replace=False,
    )
    test_targets = test_targets[selected_indices]

    rotations = sample_so3(n_analytic_orientations, rng)
    psi_samples = np.linspace(
        -np.pi,
        np.pi,
        n_analytic_psi,
        endpoint=False,
    )

    solver_kwargs = {}
    if enforce_joint_limits and hasattr(robot_cfg, "q_min"):
        solver_kwargs["limits_lower"] = robot_cfg.q_min
        solver_kwargs["limits_upper"] = robot_cfg.q_max
    ik_solver = Analytical_IK_7DoF(**solver_kwargs)

    fm = FlowMatching(cfg, norm)
    fm.load()
    print("Model loaded.")
    print(f"FM conditioning dimension: {robot_cfg.x_dim}")
    print(f"Targets: {len(test_targets)}")
    print(
        "Analytical reference samples per target before filtering: "
        f"{len(GC_BRANCHES) * n_analytic_orientations * n_analytic_psi}"
    )

    results = []
    for target_index, target_position in enumerate(test_targets):
        result = evaluate_target(
            fm=fm,
            robot_cfg=robot_cfg,
            ik=ik_solver,
            target_position=target_position,
            rotations=rotations,
            psi_samples=psi_samples,
            x_dim=robot_cfg.x_dim,
            n_samples=n_samples,
            n_steps=n_steps,
            enforce_joint_limits=enforce_joint_limits,
            correction_iters=correction_iters,
            pose_tolerance=pose_tolerance,
            acos_tolerance=acos_tolerance,
            distance_candidates=distance_candidates,
        )
        results.append(result)

        position_median = _finite_median(
            result["corrected_position_errors"]
        )
        print(
            f"Target {target_index + 1}/{len(test_targets)}: "
            f"corrected FM samples={len(result['corrected_q'])}, "
            f"analytic samples={len(result['analytic_q'])}, "
            f"position median={position_median:.3e} m"
        )
        print_target_branch_summary(result)

    print_summary(results)
    plot_comparison(results, output_path, projection=projection)

    if metrics_path is None:
        metrics_path = Path(output_path).with_suffix(".npz")
    save_metrics(results, metrics_path)

    print(f"Saved figure to: {output_path}")
    print(
        "Saved branch projection figure to: "
        f"{Path(output_path).with_name(Path(output_path).stem + '_joint_projection' + Path(output_path).suffix)}"
    )
    print(f"Saved metrics to: {metrics_path}")
    return results


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--robot_name", default="kuka_iiwa_14_position")
    parser.add_argument("--n_targets", type=int, default=1)
    parser.add_argument("--n_samples", type=int, default=400_000)
    parser.add_argument("--n_steps", type=int, default=100)
    parser.add_argument("--n_analytic_orientations", type=int, default=512)
    parser.add_argument("--n_analytic_psi", type=int, default=512)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--enforce_joint_limits", action="store_true")
    parser.add_argument("--correction_iters", type=int, default=3)
    parser.add_argument("--pose_tolerance", type=float, default=1e-5)
    parser.add_argument("--acos_tolerance", type=float, default=1e-8)
    parser.add_argument("--distance_candidates", type=int, default=64)
    parser.add_argument("--joint_x", type=int, default=6)
    parser.add_argument("--joint_y", type=int, default=7)
    parser.add_argument(
        "--output",
        default="model/analytic_ik/tests/figures/fm_vs_analytic_4d_branches.png",
    )
    parser.add_argument("--metrics", default=None)
    args = parser.parse_args()

    if not (1 <= args.joint_x <= 7 and 1 <= args.joint_y <= 7):
        raise ValueError("--joint_x and --joint_y must be in [1, 7].")

    cfg = FMConfig(robot_name=args.robot_name)
    evaluate_4d(
        cfg,
        n_targets=args.n_targets,
        n_samples=args.n_samples,
        n_steps=args.n_steps,
        n_analytic_orientations=args.n_analytic_orientations,
        n_analytic_psi=args.n_analytic_psi,
        seed=args.seed,
        enforce_joint_limits=args.enforce_joint_limits,
        correction_iters=args.correction_iters,
        pose_tolerance=args.pose_tolerance,
        acos_tolerance=args.acos_tolerance,
        distance_candidates=args.distance_candidates,
        output_path=args.output,
        metrics_path=args.metrics,
        projection=(args.joint_x - 1, args.joint_y - 1),
    )


if __name__ == "__main__":
    main()