"""
cluster qs generated by flow-matching model where
each component is one self-motion manifold (SMM)
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# scipy
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components

# flow matching model
from model.flow_matching import FMConfig, FlowMatching, load_data

# wrap pi for torus distance
def wrap_pi(a: np.ndarray) -> np.ndarray:
    return (a + np.pi) % (2 * np.pi) - np.pi

# torus metric
def torus_dist(a, b):
    "pairwise torus distance: a: (N, q_dim), b: (N, q_dim) -> (N, N)"
    d = wrap_pi(a[:, None, :] - b[None, :, :])
    return np.linalg.norm(d, axis=-1)

# filter out extremal qs
def filter_samples(qs, x, robot_cfg, fk_tol=0.01):
    T = np.array(robot_cfg.robot.fkine(qs).A)

    if robot_cfg.name == "3R":
        pos_pred = T[:, :2, 3]
        err = np.linalg.norm(pos_pred - x[:2], axis=-1)
        print(f"raw error mean: {err.mean()}")
        print(f"raw error min: {err.min()}")
        return qs[err < fk_tol], (err < fk_tol).mean()

    elif robot_cfg.name == "7R_pose":
        # err includes position error and orientation error
        postion_pred = T[:, :3, 3]
        R_pred_6d = T[:, :3, :2]

        R_true_6d = np.stack([x[3:6], x[6:9]], axis=1)

        R_true = np.column_stack([
                R_true_6d[:, 0],
                R_true_6d[:, 1],
                np.cross(R_true_6d[:, 0], R_true_6d[:, 1]),
            ])

        R_pred = np.concatenate([
                R_pred_6d,
                np.cross(
                    R_pred_6d[:, :, 0],
                    R_pred_6d[:, :, 1],
                )[:, :, None],
            ], axis=2)


        position_errors = np.linalg.norm(T[:, :3, 3] - x[:3], axis=-1)
        R_error = R_true.T @ R_pred
        
        cos_angle = (
            np.trace(R_error, axis1=1, axis2=2) - 1.0
        ) / 2.0
    
        cos_angle = np.clip(cos_angle, -1.0, 1.0)
    
        ori_errors = np.arccos(cos_angle)

        error = 0.5 * (position_errors / robot_cfg.x_max + ori_errors / np.pi)

        return qs[error < fk_tol], (err < fk_tol).mean()

    else:
        raise NameError("robot name is invalid")

# cluster torus
def cluster_torus(qs, eps=0.5, min_frac=0.02):
    n = len(qs)

    if n <= 0:
        raise ValueError("length of qs should be positive")

    # create something like adjacent matrix
    d = torus_dist(qs, qs)
    # efficently store non-zero parts
    adj = csr_matrix(d < eps)
    _, labels = connected_components(adj, directed=False)

    # drop tiny cluster as outliers
    keep = []
    for c in np.unique(labels):
        if (labels == c).sum() >= max(2, min_frac * n):
            keep.append(c)
    out = np.full(n, -1, dtype=int)

    for new, c in enumerate(keep):
        out[labels == c] = new

    k = len(keep)

    gap = np.nan
    if k >= 2:
        gap = min(
            torus_dist(qs[out == i], qs[out == j]).min()
            for i in range(k) for j in range(i + 1, k)
        )
    return out, k, gap

def plot_clusters(qs_keep, labels):
    fig, ax = plt.subplots(figsize=(12, 5))

    for lb in np.unique(labels):
        mask = labels == lb

        ax.scatter(
            qs_keep[mask, 1],
            qs_keep[mask, 2],
            label=f"Cluster {lb}",
        )

    ax.set_xlabel(r'$\theta_2$ (rad)')
    ax.set_ylabel(r'$\theta_3$ (rad)')

    ax.set_xlim(-np.pi - 1, np.pi + 1)
    ax.set_ylim(-np.pi - 1, np.pi + 1)

    ax.set_aspect("equal", adjustable="box")
    ax.grid(True, alpha=0.3)
    ax.legend()

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    # configs
    cfg = FMConfig(robot_name="3R")
    robot_cfg = cfg.load_robot
    print(f"FM and Robot configs are loaded")

    # fm model
    _, _, norm = load_data(cfg)
    fm = FlowMatching(cfg, norm)
    fm.load()
    print(f'model loaded')

    # sampling
    x = np.array([1, 1.5])
    print(f"target postion: {x}")
    qs = fm.sample(x, n_samples=2000, n_steps=100)

    # clustering
    qs_wrapped = wrap_pi(qs)
    qs_keep, keep_frac = filter_samples(
        qs = qs_wrapped,
        x = x,
        robot_cfg=robot_cfg,
        fk_tol=0.02
    )
    print(f"keep frac = {keep_frac}")
    # print(f"qs keep: {qs_keep}")
    labels, k, gap = cluster_torus(qs_keep, eps = 1.0)

    print(f"labels: {labels}")
    print(f"k : {k}")
    print(f"gap: {gap}")

    plot_clusters(qs_keep, labels)
